sudo: required
virtualenv:
  system_site_packages: true
dist: trusty
language: python
python:
  - 3.4
addons:
  apt:
    packages: [ python3 ]
before_install:
  - git clone https://github.com/ops-snappy/snapcraft
  - cd snapcraft && ./setup.py install
install:
  - snapcraft/bin/snapcraft
script: true
