sudo: required
dist: trusty
language: python
python:
  - 3.4
before_install:
  - git clone https://github.com/ops-snappy/snapcraft
  - pip install docopt requests pyyaml
  - cd snapcraft && ./setup.py install
install:
  - snapcraft
script: true
