sudo: required
virtualenv:
  system_site_packages: true
dist: trusty
language: C
addons:
  apt:
    packages: [ python3, python3-pip, python3-requests ]
before_install:
  - git clone https://github.com/ops-snappy/snapcraft
  - cd snapcraft && sudo python3 setup.py install
  - sudo pip3 install docopt
install:
  - snapcraft
script: true
