name: openswitch
version: 0.2.0
summary: OpenSwitch NOS
description: OpenSwitch Network Operating System suite
icon: OpenSwitchLogo.png

# uses github mirrors for speed instead of the canonical git.openswitch.net
# repos
parts:
  # schema files required for ops-openvswitch
  ops:
    plugin: make
    source: git://github.com/ops-snappy/ops

  # based on upstream recipe:
  # https://github.com/open-switch/ops-build/blob/master/yocto/openswitch/meta-distro-openswitch/recipes-ops/openvswitch/ops-openvswitch.bb
  # without the patches though and without libjemalloc alternate malloc impl
  # (performance improvement for ovsdb)
  # also this is built with simulator provider for now to defer integration of
  # BCM's OpenNSL
  ops-openvswitch:
    plugin: x-autotools
    configflags:
      - "OPS_BUILD=1"
      - "BUILD_OVS_VSWITCHD=0"
      - "BUILD_PLUGINS_LIB=1"
      - "--prefix=/usr"
      - "--enable-shared"
      - "--disable-static"
      - "--enable-simulator-provider"
    source: git://github.com/ops-snappy/ops-openvswitch
    stage-packages:
      - libyaml-dev
    build-packages:
      - pkg-config
      - libjemalloc-dev
      - libltdl-dev
      - libssl-dev
    after: [ ops ]
    precmd: ['bash', '-c', 'cp -v ../../../stage/usr/share/openvswitch/*.{extschema,ovsschema,xml} vswitchd/']

