name: openswitch
version: 0.2.0
summary: OpenSwitch NOS
description: OpenSwitch Network Operating System suite
icon: OpenSwitchLogo.png

apps:
  start-openswitch:
    command: usr/sbin/start-openswitch
    plugs: [ networking ]
  stop-openswitch:
    command: usr/sbin/stop-openswitch
    plugs: [ networking ]

plugs:
# TODO - come up with a better security profile for the daemons.
  networking:
    interface: old-security
    security-template: unconfined

# uses github mirrors for speed instead of the canonical git.openswitch.net
# repos
parts:
  # schema files required for ops-openvswitch
  ops:
    plugin: make
    source: git://github.com/ops-snappy/ops

  # based on upstream recipe:
  # https://github.com/open-switch/ops-build/blob/master/yocto/openswitch/meta-distro-openswitch/recipes-ops/openvswitch/ops-openvswitch.bb
  # without the patches though and without libjemalloc alternate malloc impl
  # (performance improvement for ovsdb)
  # also this is built with simulator provider for now to defer integration of
  # BCM's OpenNSL
  ops-openvswitch:
    plugin: x-autotools
    configflags:
      - "OPS_BUILD=1"
      - "OPEN_HALON_BUILD=1"
      - "BUILD_OVS_VSWITCHD=0"
      - "BUILD_PLUGINS_LIB=1"
      - "--prefix=/usr"
      - "--enable-shared"
      - "--disable-static"
      - "--enable-simulator-provider"
    source: git://github.com/ops-snappy/ops-openvswitch
    stage-packages:
      - libyaml-dev
    build-packages:
      - pkg-config
      - libjemalloc-dev
      - libltdl-dev
      - libssl-dev
    after: [ ops ]
    precmd: ['bash', '-c', 'cp -v ../../../stage/usr/share/openvswitch/*.{extschema,ovsschema,xml} vswitchd/']

    # TODO: Figure out why build is not installing the libraries.
    #       In the meantime, we'll install them manually.
    postcmd: ['bash', '-c', '(test -d ../install/usr/lib || mkdir -p ../install/usr/bin) && cp -a ovsdb/.libs/*.so* ../install/usr/lib && cp -a lib/.libs/*.so* ../install/usr/lib && cp -a ofproto/.libs/*.so* ../install/usr/lib && cp -a vtep/.libs/*.so* ../install/usr/lib && cp -a plugins/.libs/*.so* ../install/usr/lib']

  ops-init:
    plugin: make
    source: src/ops-init

